In [2]:
%load_ext sql

In [3]:
%sql postgresql://appdev@data3/appdev

'Connected: appdev@appdev'

In [6]:
%sql SELECT * FROM information_schema.tables WHERE table_schema='f1db';

13 rows affected.

[('appdev', 'f1db', 'circuits', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('appdev', 'f1db', 'constructorresults', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('appdev', 'f1db', 'constructors', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('appdev', 'f1db', 'constructorstandings', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('appdev', 'f1db', 'drivers', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('appdev', 'f1db', 'driverstandings', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('appdev', 'f1db', 'laptimes', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('appdev', 'f1db', 'pitstops', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('appdev', 'f1db', 'qualifying', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('appdev', 'f1db', 'races', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('appdev', 'f1db', 'results', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('appdev', 'f1db', 'seasons', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None),
 ('appdev', 'f1db', 'status', 'BASE TABLE', None, None, None, None, None, 'YES', 'NO', None)]

# Exercises

1. Using a single join and a grouping, write a query that allows you to find the forename, surname, driverid and the total number of wins for each driver in the f1db schema.

In [39]:
%%sql 
SELECT forename, surname, drivers.driverid, count(*)
FROM results INNER JOIN drivers ON results.driverid=drivers.driverid 
WHERE position='1'
GROUP BY drivers.driverid
ORDER BY count DESC

107 rows affected.

[('Michael', 'Schumacher', 30, 91),
 ('Lewis', 'Hamilton', 1, 60),
 ('Alain', 'Prost', 117, 51),
 ('Sebastian', 'Vettel', 20, 46),
 ('Ayrton', 'Senna', 102, 41),
 ('Fernando', 'Alonso', 4, 32),
 ('Nigel', 'Mansell', 95, 31),
 ('Jackie', 'Stewart', 328, 27),
 ('Jim', 'Clark', 373, 25),
 ('Niki', 'Lauda', 182, 25),
 ('Juan', 'Fangio', 579, 24),
 ('Nico', 'Rosberg', 3, 23),
 ('Nelson', 'Piquet', 137, 23),
 ('Damon', 'Hill', 71, 22),
 ('Mika', 'Häkkinen', 57, 20),
 ('Kimi', 'Räikkönen', 8, 20),
 ('Stirling', 'Moss', 475, 16),
 ('Jenson', 'Button', 18, 15),
 ('Graham', 'Hill', 289, 14),
 ('Jack', 'Brabham', 356, 14),
 ('Emerson', 'Fittipaldi', 224, 14),
 ('Alberto', 'Ascari', 647, 13),
 ('David', 'Coulthard', 14, 13),
 ('Mario', 'Andretti', 207, 12),
 ('Alan', 'Jones', 178, 12),
 ('Carlos', 'Reutemann', 199, 12),
 ('Jacques', 'Villeneuve', 35, 11),
 ('Felipe', 'Massa', 13, 11),
 ('Rubens', 'Barrichello', 22, 11),
 ('Ronnie', 'Peterson', 238, 10),
 ('Gerhard', 'Berger', 77, 10),
 ('Jody', 'Scheckter', 222, 10),
 ('James', 'Hunt', 231, 10),
 ('Mark', 'Webber', 17, 9),
 ('Denny', 'Hulme', 304, 8),
 ('Jacky', 'Ickx', 235, 8),
 ('Juan', 'Pablo Montoya', 31, 7),
 ('René', 'Arnoux', 163, 7),
 ('Gilles', 'Villeneuve', 203, 6),
 ('John', 'Surtees', 341, 6),
 ('Tony', 'Brooks', 479, 6),
 ('Ralf', 'Schumacher', 23, 6),
 ('Jochen', 'Rindt', 358, 6),
 ('Riccardo', 'Patrese', 119, 6),
 ('Jacques', 'Laffite', 172, 6),
 ('Michele', 'Alboreto', 105, 5),
 ('Daniel', 'Ricciardo', 817, 5),
 ('Nino', 'Farina', 642, 5),
 ('John', 'Watson', 187, 5),
 ('Keke', 'Rosberg', 177, 5),
 ('Clay', 'Regazzoni', 223, 5),
 ('Eddie', 'Irvine', 56, 4),
 ('Dan', 'Gurney', 364, 4),
 ('Bruce', 'McLaren', 360, 4),
 ('Johnny', 'Herbert', 65, 3),
 ('Didier', 'Pironi', 202, 3),
 ('Heinz-Harald', 'Frentzen', 49, 3),
 ('Phil', 'Hill', 403, 3),
 ('Mike', 'Hawthorn', 578, 3),
 ('Thierry', 'Boutsen', 123, 3),
 ('Peter', 'Collins', 581, 3),
 ('Giancarlo', 'Fisichella', 21, 3),
 ('Jean-Pierre', 'Jabouille', 219, 2),
 ('José Froilán', 'González', 498, 2),
 ('Wolfgang', 'von Trips', 476, 2),
 ('Bill', 'Vukovich', 657, 2),
 ('Pedro', 'Rodríguez', 345, 2),
 ('Maurice', 'Trintignant', 427, 2),
 ('Patrick', 'Tambay', 175, 2),
 ('Jo', 'Siffert', 346, 2),
 ('Valtteri', 'Bottas', 822, 2),
 ('Max', 'Verstappen', 830, 2),
 ('Elio', 'de Angelis', 173, 2),
 ('Patrick', 'Depailler', 221, 2),
 ('Peter', 'Revson', 309, 2),
 ('Peter', 'Gethin', 320, 1),
 ('Jo', 'Bonnier', 347, 1),
 ('Jim', 'Rathmann', 509, 1),
 ('Robert', 'Kubica', 9, 1),
 ('Luigi', 'Fagioli', 786, 1),
 ('Lorenzo', 'Bandini', 385, 1),
 ('Lee', 'Wallard', 766, 1),
 ('Heikki', 'Kovalainen', 5, 1),
 ('Gunnar', 'Nilsson', 255, 1),
 ('Jochen', 'Mass', 200, 1),
 ('Jean', 'Alesi', 55, 1),
 ('Jarno', 'Trulli', 15, 1),
 ('Jean-Pierre', 'Beltoise', 306, 1),
 ('Jimmy', 'Bryan', 525, 1),
 ('Ludovico', 'Scarfiotti', 375, 1),
 ('Luigi', 'Musso', 577, 1),
 ('Richie', 'Ginther', 386, 1),
 ('Bob', 'Sweikert', 628, 1),
 ('Troy', 'Ruttman', 526, 1),
 ('Innes', 'Ireland', 404, 1),
 ('Pastor', 'Maldonado', 813, 1),
 ('Johnnie', 'Parsons', 593, 1),
 ('Olivier', 'Panis', 44, 1),
 ('Rodger', 'Ward', 449, 1),
 ('Piero', 'Taruffi', 641, 1),
 ('François', 'Cevert', 327, 1),
 ('Giancarlo', 'Baghetti', 394, 1),
 ('Vittorio', 'Brambilla', 230, 1),
 ('Carlos', 'Pace', 250, 1),
 ('Sam', 'Hanks', 611, 1),
 ('Pat', 'Flaherty', 559, 1),
 ('Alessandro', 'Nannini', 145, 1)]

2. Write a query that joins the tables results, constructors and drivers to show the amount of times a driver has driven a car from a constructor. In other words how many times one driver (for instance Schumacher) has driven a constructor (for instance Mercedes). Your table should have three fields: drivers.driverref, constructors.name and count(*) (showing the number of times the driver has driven the constructor).
Hint: You can group on more than one value

In [159]:
%%sql
SELECT drivers.driverref, constructors.name, count(*)
FROM results 
NATURAL JOIN drivers
INNER JOIN constructors
ON results.constructorid=constructors.constructorid
GROUP BY drivers.driverref, constructors.name
ORDER BY count(*) DESC, driverref

54 rows affected.

[('hamilton', 'Mercedes', 74),
 ('perez', 'Force India', 74),
 ('raikkonen', 'Ferrari', 74),
 ('ricciardo', 'Red Bull', 74),
 ('massa', 'Williams', 73),
 ('button', 'McLaren', 60),
 ('bottas', 'Williams', 59),
 ('hulkenberg', 'Force India', 59),
 ('rosberg', 'Mercedes', 59),
 ('grosjean', 'Lotus F1', 57),
 ('ericsson', 'Sauber', 55),
 ('sainz', 'Toro Rosso', 55),
 ('vettel', 'Ferrari', 55),
 ('alonso', 'McLaren', 52),
 ('kvyat', 'Toro Rosso', 50),
 ('nasr', 'Sauber', 40),
 ('maldonado', 'Lotus F1', 38),
 ('grosjean', 'Haas F1 Team', 36),
 ('jolyon_palmer', 'Renault', 36),
 ('max_verstappen', 'Red Bull', 32),
 ('kvyat', 'Red Bull', 23),
 ('max_verstappen', 'Toro Rosso', 23),
 ('gutierrez', 'Haas F1 Team', 21),
 ('kevin_magnussen', 'Renault', 21),
 ('wehrlein', 'Manor Marussia', 21),
 ('kevin_magnussen', 'McLaren', 20),
 ('alonso', 'Ferrari', 19),
 ('gutierrez', 'Sauber', 19),
 ('sutil', 'Sauber', 19),
 ('vergne', 'Toro Rosso', 19),
 ('vettel', 'Red Bull', 19),
 ('stevens', 'Manor Marussia', 18),
 ('button', 'Brawn', 17),
 ('raikkonen', 'Lotus F1', 17),
 ('chilton', 'Marussia', 16),
 ('ericsson', 'Caterham', 16),
 ('kobayashi', 'Caterham', 16),
 ('bottas', 'Mercedes', 15),
 ('hulkenberg', 'Renault', 15),
 ('jules_bianchi', 'Marussia', 15),
 ('kevin_magnussen', 'Haas F1 Team', 15),
 ('ocon', 'Force India', 15),
 ('stroll', 'Williams', 15),
 ('vandoorne', 'McLaren', 15),
 ('merhi', 'Manor Marussia', 13),
 ('wehrlein', 'Sauber', 13),
 ('haryanto', 'Manor Marussia', 12),
 ('ocon', 'Manor Marussia', 9),
 ('grosjean', 'Renault', 7),
 ('rossi', 'Manor Marussia', 5),
 ('giovinazzi', 'Sauber', 2),
 ('kobayashi', 'Toyota', 2),
 ('gasly', 'Toro Rosso', 1),
 ('lotterer', 'Caterham', 1)]

 
4. Now we have found the most driven vehicles even for those who didn't finish the race. Extend the query from 2 by removing all tuples from the result where the status is not "Finished".

In [104]:
%%sql
SELECT drivers.driverref, constructors.name, count(*)
FROM results 
NATURAL JOIN drivers
INNER JOIN constructors
ON results.constructorid=constructors.constructorid
NATURAL JOIN status
WHERE status != 'Finished'
GROUP BY drivers.driverref, constructors.name
ORDER BY count(*) DESC, driverref

53 rows affected.

[('ericsson', 'Sauber', 48),
 ('alonso', 'McLaren', 39),
 ('kvyat', 'Toro Rosso', 39),
 ('button', 'McLaren', 37),
 ('sainz', 'Toro Rosso', 37),
 ('perez', 'Force India', 36),
 ('grosjean', 'Lotus F1', 34),
 ('massa', 'Williams', 32),
 ('nasr', 'Sauber', 31),
 ('jolyon_palmer', 'Renault', 30),
 ('maldonado', 'Lotus F1', 27),
 ('hulkenberg', 'Force India', 26),
 ('grosjean', 'Haas F1 Team', 25),
 ('raikkonen', 'Ferrari', 21),
 ('wehrlein', 'Manor Marussia', 20),
 ('gutierrez', 'Haas F1 Team', 19),
 ('gutierrez', 'Sauber', 18),
 ('kevin_magnussen', 'Renault', 18),
 ('ricciardo', 'Red Bull', 18),
 ('stevens', 'Manor Marussia', 18),
 ('bottas', 'Williams', 17),
 ('sutil', 'Sauber', 17),
 ('chilton', 'Marussia', 15),
 ('ericsson', 'Caterham', 15),
 ('kobayashi', 'Caterham', 15),
 ('jules_bianchi', 'Marussia', 14),
 ('kvyat', 'Red Bull', 14),
 ('merhi', 'Manor Marussia', 13),
 ('haryanto', 'Manor Marussia', 12),
 ('kevin_magnussen', 'Haas F1 Team', 12),
 ('max_verstappen', 'Toro Rosso', 12),
 ('vandoorne', 'McLaren', 12),
 ('wehrlein', 'Sauber', 12),
 ('stroll', 'Williams', 11),
 ('hulkenberg', 'Renault', 10),
 ('max_verstappen', 'Red Bull', 10),
 ('vergne', 'Toro Rosso', 9),
 ('kevin_magnussen', 'McLaren', 8),
 ('ocon', 'Manor Marussia', 8),
 ('ocon', 'Force India', 7),
 ('vettel', 'Ferrari', 7),
 ('grosjean', 'Renault', 6),
 ('hamilton', 'Mercedes', 6),
 ('rosberg', 'Mercedes', 6),
 ('rossi', 'Manor Marussia', 4),
 ('vettel', 'Red Bull', 4),
 ('raikkonen', 'Lotus F1', 3),
 ('alonso', 'Ferrari', 2),
 ('giovinazzi', 'Sauber', 2),
 ('bottas', 'Mercedes', 1),
 ('button', 'Brawn', 1),
 ('gasly', 'Toro Rosso', 1),
 ('lotterer', 'Caterham', 1)]

5. Create a third (and new) query that finds the amount of milliseconds spent in pitstop (see the pitstops relation) by each unique combinations of driverid and raceid.

In [152]:
%%sql CREATE VIEW pitstop_durations AS 
SELECT results.driverid, results.raceid, sum(pitstops.milliseconds)
FROM pitstops
INNER JOIN results
ON pitstops.raceid=results.raceid
GROUP BY results.driverid, results.raceid
ORDER BY sum DESC, results.driverid, results.raceid

Done.

[]

In [153]:
%sql SELECT * FROM pitstop_durations LIMIT 20

20 rows affected.

[(1, 967, Decimal('63535637')),
 (3, 967, Decimal('63535637')),
 (4, 967, Decimal('63535637')),
 (8, 967, Decimal('63535637')),
 (13, 967, Decimal('63535637')),
 (18, 967, Decimal('63535637')),
 (20, 967, Decimal('63535637')),
 (154, 967, Decimal('63535637')),
 (807, 967, Decimal('63535637')),
 (815, 967, Decimal('63535637')),
 (817, 967, Decimal('63535637')),
 (821, 967, Decimal('63535637')),
 (822, 967, Decimal('63535637')),
 (825, 967, Decimal('63535637')),
 (826, 967, Decimal('63535637')),
 (828, 967, Decimal('63535637')),
 (830, 967, Decimal('63535637')),
 (831, 967, Decimal('63535637')),
 (832, 967, Decimal('63535637')),
 (835, 967, Decimal('63535637'))]

Time to put everything together. Use the query for 4 as a join subquery in query 3 (see slides on "a query within a query") to find the total amount of pitstop time, for each result in query 3

In [170]:
%%sql
SELECT drivers.driverref, constructors.name, count(*), milliseconds
FROM results 
NATURAL JOIN drivers
INNER JOIN constructors
ON results.constructorid=constructors.constructorid
INNER JOIN pitstop_durations
ON results.driverid = pitstop_durations.driverid
GROUP BY drivers.driverref, constructors.name, milliseconds

LIMIT 100

100 rows affected.

[('alonso', 'Ferrari', 129, 5137718),
 ('alonso', 'Ferrari', 129, 5293529),
 ('alonso', 'Ferrari', 129, 5464461),
 ('alonso', 'Ferrari', 129, 5570760),
 ('alonso', 'Ferrari', 129, 5613994),
 ('alonso', 'Ferrari', 129, 5631942),
 ('alonso', 'Ferrari', 129, 5675381),
 ('alonso', 'Ferrari', 129, 5967699),
 ('alonso', 'Ferrari', 129, 6015338),
 ('alonso', 'Ferrari', 129, 6028432),
 ('alonso', 'Ferrari', 129, 6061966),
 ('alonso', 'Ferrari', 129, 6100016),
 ('alonso', 'Ferrari', 129, 6152898),
 ('alonso', 'Ferrari', 129, 6600113),
 ('alonso', 'Ferrari', 129, 6790283),
 ('alonso', 'Ferrari', 129, 7220184),
 ('alonso', 'Ferrari', 129, 8872040),
 ('alonso', 'Ferrari', 258, None),
 ('alonso', 'McLaren', 129, 5897981),
 ('alonso', 'McLaren', 129, 5922234),
 ('alonso', 'McLaren', 129, 5943909),
 ('alonso', 'McLaren', 129, 5986571),
 ('alonso', 'McLaren', 129, 6031144),
 ('alonso', 'McLaren', 129, 6057936),
 ('alonso', 'McLaren', 129, 6350503),
 ('alonso', 'McLaren', 129, 6419064),
 ('alonso', 'McLaren', 129, 6707519),
 ('alonso', 'McLaren', 129, 7038148),
 ('alonso', 'McLaren', 129, 7254209),
 ('alonso', 'McLaren', 129, 7495124),
 ('alonso', 'McLaren', 129, 10905767),
 ('alonso', 'McLaren', 5031, None),
 ('bottas', 'Mercedes', 93, 4536783),
 ('bottas', 'Mercedes', 93, 4901493),
 ('bottas', 'Mercedes', 93, 4908523),
 ('bottas', 'Mercedes', 93, 5062922),
 ('bottas', 'Mercedes', 93, 5099276),
 ('bottas', 'Mercedes', 93, 5288743),
 ('bottas', 'Mercedes', 93, 5457311),
 ('bottas', 'Mercedes', 93, 5604937),
 ('bottas', 'Mercedes', 93, 5653771),
 ('bottas', 'Mercedes', 93, 5904966),
 ('bottas', 'Mercedes', 93, 5999175),
 ('bottas', 'Mercedes', 93, 6289857),
 ('bottas', 'Mercedes', 93, 7412344),
 ('bottas', 'Mercedes', 93, 7439477),
 ('bottas', 'Mercedes', 93, None),
 ('bottas', 'Williams', 93, 4699104),
 ('bottas', 'Williams', 93, 4728684),
 ('bottas', 'Williams', 93, 4791022),
 ('bottas', 'Williams', 93, 5081427),
 ('bottas', 'Williams', 93, 5104588),
 ('bottas', 'Williams', 93, 5283148),
 ('bottas', 'Williams', 93, 5301656),
 ('bottas', 'Williams', 93, 5470534),
 ('bottas', 'Williams', 93, 5511718),
 ('bottas', 'Williams', 93, 5528169),
 ('bottas', 'Williams', 93, 5550923),
 ('bottas', 'Williams', 93, 5553811),
 ('bottas', 'Williams', 93, 5612214),
 ('bottas', 'Williams', 93, 5626349),
 ('bottas', 'Williams', 93, 5633252),
 ('bottas', 'Williams', 93, 5643703),
 ('bottas', 'Williams', 93, 5664035),
 ('bottas', 'Williams', 93, 5748766),
 ('bottas', 'Williams', 93, 5894358),
 ('bottas', 'Williams', 93, 5971499),
 ('bottas', 'Williams', 93, 5976408),
 ('bottas', 'Williams', 93, 5991893),
 ('bottas', 'Williams', 93, 6014619),
 ('bottas', 'Williams', 93, 6020083),
 ('bottas', 'Williams', 93, 6035777),
 ('bottas', 'Williams', 93, 6097014),
 ('bottas', 'Williams', 93, 6111511),
 ('bottas', 'Williams', 93, 6131772),
 ('bottas', 'Williams', 93, 6136202),
 ('bottas', 'Williams', 93, 6144448),
 ('bottas', 'Williams', 93, 6145288),
 ('bottas', 'Williams', 93, 6169630),
 ('bottas', 'Williams', 93, 6351209),
 ('bottas', 'Williams', 93, 6450213),
 ('bottas', 'Williams', 93, 6570718),
 ('bottas', 'Williams', 93, 6604209),
 ('bottas', 'Williams', 93, 6816794),
 ('bottas', 'Williams', 93, 6826402),
 ('bottas', 'Williams', 93, 7269860),
 ('bottas', 'Williams', 93, 7316322),
 ('bottas', 'Williams', 93, 8842229),
 ('bottas', 'Williams', 93, 10906627),
 ('bottas', 'Williams', 1581, None),
 ('button', 'Brawn', 118, 4252092),
 ('button', 'Brawn', 118, 4584572),
 ('button', 'Brawn', 118, 5015613),
 ('button', 'Brawn', 118, 5184848),
 ('button', 'Brawn', 118, 5311917),
 ('button', 'Brawn', 118, 5508182),
 ('button', 'Brawn', 118, 5572086),
 ('button', 'Brawn', 118, 5655784),
 ('button', 'Brawn', 118, 5661881),
 ('button', 'Brawn', 118, 5786202)]